### ISSUE TITLE
The Hell is this

### ISSUE THREAD

**Issue by DusterTheFirst** [MrBob101/MrBob101.github.io#5]
```js
var correctuname = "document.write(unescape('%44%65%76%65%6C%6F%70%65%72'));",
    correctpsw = "root";
```

**Comment by MrBob101** [comment]
Security

**Comment by DusterTheFirst** [comment]
No it isn't
You don't know js

**Comment by DusterTheFirst** [comment]
You don't put code in quotes

**Comment by DusterTheFirst** [comment]
It should be 
```js
var correctuname = document.write(unescape('%44%65%76%65%6C%6F%70%65%72'));,
    correctpsw = "root";
```

code doesn't work in quotes

**Comment by MrBob101** [comment]
Why won't This work as encryption

<script type="text/javascript">

</script>
<noscript><i>Javascript required</i></noscript>

**Comment by MrBob101** [comment]
Look At my Update password folders. Why doesn't it work????????

**Comment by DusterTheFirst** [comment]
YOU ARE A GODDAMN IDIOT. LEARN JAVASCRIPT. DTOP FUCKING WITH MY SHIT. IT WAS FINE BEFORE. AND ITS NOT WORKING BECAUSE YOU ARE A FUCKING IDIOT

**Comment by DusterTheFirst** [comment]
I SPENT HOURS WORKING ON THIS SHIT, JUST FOR YOU TO DELETE IT AND REPLACE IT WITH SHIT ALL

**Comment by MrBob101** [comment]
Don't worry I can recover it. Just tying to add security

**Comment by DusterTheFirst** [comment]
I TOLD YOU THE TWO LINES YOU COULD CHANGE, AND YOU FUCKING DELETE THE WHOLE GODDAMN FILE

**Comment by MrBob101** [comment]
Btw. It is still your code, just encrypted with java script. So what can I do?

**Comment by MrBob101** [comment]
Fixed
